# taskflow-minimal/docker-compose.yml
services:
  # 🗄️ DATABASE
  taskflow-db-minimal:
    image: postgres:15-alpine
    container_name: taskflow-db-minimal
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: paul
      POSTGRES_PASSWORD: paul123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paul -d taskflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🚀 API
  taskflow-api-minimal:
    build: .
    container_name: taskflow-api-minimal
    ports:
      - "8000:8000"
    depends_on:
      taskflow-db-minimal:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: